DWAPlannerROS:
  # Robot configuration parameters
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_th: 3.2

  max_vel_x: 1.0 #1.0
  min_vel_x: 0.1
  max_vel_y: 0.1
  min_vel_y: -0.1

  max_trans_vel: 0.5 #0.5
  min_trans_vel: 0.1
  max_rot_vel: 1.0
  min_rot_vel: 0.4

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.5
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 10.0
  vtheta_samples: 30.0