DWAPlannerROS:
  # Robot configuration parameters
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_th: 3.2

  max_vel_x: 0.55
  min_vel_x: 0.0
  max_vel_y: 0.1
  min_vel_y: -0.1

  max_trans_vel: 0.5
  min_trans_vel: 0.1
  max_rot_vel: 1.0
  min_rot_vel: 0.4

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 3.14
  xy_goal_tolerance: 0.5
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 1.7
  sim_granularity: 0.017
  vx_samples: 3.0
  vtheta_samples: 3.0

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.3